name: Trigger HF Space crawl every 40 minutes and cleanup

on:
  schedule:
    - cron: '*/40 * * * *'
  workflow_dispatch:

jobs:
  crawl-and-clean:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      HF_SPACE_BASE_URL: ${{ secrets.HF_SPACE_BASE_URL || vars.HF_SPACE_BASE_URL }}
    steps:
      - name: Validate HF_SPACE_BASE_URL
        run: |
          if [ -z "$HF_SPACE_BASE_URL" ]; then
            echo "::warning::HF_SPACE_BASE_URL not set. Configure in Repo Settings → Secrets and variables → Actions (Secret or Variable). Skipping scheduled crawl.";
          else
            echo "Using HF_SPACE_BASE_URL=$HF_SPACE_BASE_URL";
          fi
      - name: Ping health (keepalive)
        if: ${{ env.HF_SPACE_BASE_URL != '' }}
        run: |
          curl -fsS "$HF_SPACE_BASE_URL/health" || true
      - name: Trigger crawl (default sources, concurrency=3)
        if: ${{ env.HF_SPACE_BASE_URL != '' }}
        run: |
          curl -fsS -X POST "$HF_SPACE_BASE_URL/api/news/crawl?concurrency=3" -H "Content-Type: application/json" || true
      - name: Trigger prioritizer (queue new items)
        if: ${{ env.HF_SPACE_BASE_URL != '' }}
        run: |
          curl -fsS -X POST "$HF_SPACE_BASE_URL/api/news/prioritize" -H "Content-Type: application/json" || true
      - name: Trigger summarizer batch (process queue)
        if: ${{ env.HF_SPACE_BASE_URL != '' }}
        run: |
          curl -fsS -X POST "$HF_SPACE_BASE_URL/api/news/summarize?concurrency=1&batch=true" -H "Content-Type: application/json" || true
      - name: Cleanup placeholder summaries (daily safety)
        if: ${{ github.event_name == 'schedule' && env.HF_SPACE_BASE_URL != '' }}
        run: |
          # This will delete rows whose summary equals the placeholder string
          curl -fsS -X POST "$HF_SPACE_BASE_URL/api/news/cleanup-placeholders" -H "Content-Type: application/json" || true